courses/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
	url(r'^$', views.course_list, name='list'),
	url(r'(?P<course_pk>\d+)/(?P<step_pk>\d+)/$', views.step_detail, name='step'),
	url(r'(?P<pk>\d+)/$', views.course_detail, name='detail'),
	url(r'^course/new/$', views.new_course, name='new_course'),
	url(r'^course/(?P<pk>[0-9]+)/edit/$', views.course_edit, name='course_edit'),
	# url(r'^course/edit/$', views.edit_course, name='edit_course'),
]

learning_site/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
# from api import CourseResource
from django.contrib import admin
from views import cslist


from . import views

urlpatterns = [
    url(r'^$', views.home),
	url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^cslist/', cslist, name='cslist'),
    url(r'^about/$', 'courses.views.about', name='about'),
    url(r'^contact/$', 'courses.views.contact', name='contact'),
    url(r'^login/$', 'courses.views.login', name='login'),
    url(r'^signup/$', 'courses.views.signup', name='signup'),
    # url(r'^email/$', views.email, name="email"),
    
    url(r'^accounts/', include('allauth.urls')),
    url(r'^userdashboard/$', 'courses.views.userdashboard', name='userdashboard'),
    url(r'^mycourses/$', 'courses.views.mycourses', name='mycourses'),
    url(r'^users/$', 'courses.views.users', name='users'),
    url(r'^course/new/$', 'courses.views.new_course', name='new_course'),
    url(r'^course/(?P<pk>[0-9]+)/edit/$', 'courses.views.course_edit', name='course_edit'),
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.contrib.sites.models import Site
from django.db import models

# Create your models here.
class SignUp(models.Model):
	email         = models.EmailField(max_length=100)
	full_name     = models.CharField(max_length=200, blank= True)
	created_time  = models.DateTimeField(auto_now_add = True)
	last_modified = models.DateTimeField(auto_now = True)

	def __unicode__(self):
		return self.email
		#dict = model_to_dict(self)
		#return "\'{full_name}\'<{email}>".format(**dict)

class Course(models.Model):
	created_at   = models.DateTimeField(auto_now_add = True)
	title 		 = models.CharField(max_length=250)
	description  = models.TextField()

	def __unicode__(self): # def __str__(self) it is for python 3.0
		return self.title

class Step(models.Model):
	title 		= models.CharField(max_length=200)
	description = models.TextField()
	content 	= models.TextField(blank=True, default='')
	order		= models.IntegerField(default=0)
	course 		= models.ForeignKey(Course)

	class Meta:
		ordering = ['order',]

	def __unicode__(self):
		return self.title

courses/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import SignUp, Course, Step



class CourseForm(forms.ModelForm):
	class Meta:
		model = Course
		# fields = '__all__'
		fields = ['title', 'description']	

# class StepForm(forms.ModelForm):
# 	class Meta:
# 		model = Step
# 		fields = '__all__'

# StepFormSet = inlineformset_factory(Course, Step, fields='__all__', extra=1)


class SignUpForm(forms.ModelForm):
	class Meta:
		model = SignUp
		fields = ['full_name','email']		

	def clean_email(self):
		email = self.cleaned_data.get('email')
		email_base, provider = email.split("@")
		domain, extension = provider.split('.')
		#if not domain == 'USC':		
		#	raise forms.ValidationError('Please make sure you use your USC email.')
		if not extension == "com":
			raise forms.ValidationError("Please use a valid .com, .org, .net email address")
		return email

	def clean_full_name(self):
		full_name = self.cleaned_data.get('full_name')
		return full_name

courses/views.py
from django.shortcuts import get_object_or_404, render
from django.shortcuts import redirect
from django_tables2 import RequestConfig
from courses.tables import CourseTable
from .forms import CourseForm
from .models import Course, Step

# Create your views here.

# def cslist(request):
# 	table = CourseTable(Course.objects.all())
# 	RequestConfig(request).configure(table)
# 	return render(request, 'cslist/cslist.html', {'table': table})

def course_list(request):
	courses = Course.objects.all()
	return render(request, 'courses/course_list.html', {'courses': courses})

# def cslist(request):
# 	return render (request, "cslist.html", {"table": Course.ojbects.all()})

def course_detail(request, pk):
	course = get_object_or_404(Course, pk=pk)
	return render(request, 'courses/course_detail.html', {'course': course})

def step_detail(request, course_pk, step_pk):
	step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)
	return render(request, 'courses/step_detail.html', {'step': step})


# ============== add new course =========================
def new_course(request):
	#a http POST?
	if request.method == 'POST':
		form = CourseForm(request.POST)

		if form.is_valid():
			form.save(commit=True)
			# return redirect('courses.views.course_detail', pk=post.pk)
			return redirect('courses.views.mycourses')
		else:
			print form.errors
	else:
		form = CourseForm()	
	return render(request, 'courses/new_course.html', {'form': form})


# ============= update course ============================
def course_edit(request, pk):
    course = get_object_or_404(Course, pk=pk)
    if request.method == "POST":
        form = CourseForm(request.POST, instance=course)
        if form.is_valid():
            form.save(commit=True)
            return redirect('courses.views.mycourses')
    else:
        form = CourseForm(instance=course)
    return render(request, 'courses/course_edit.html', {'form': form})


# ============= navigate about page ======================
def about(request):
	return render(request, 'about.html')

# ============= navigate contact page=====================
def contact(request):
	return render(request, 'contact_us.html')


# ============= register user from default 
# ============= we are not using this view ==============
def signup(request):
	title = 'Welcome'
	if request.user.is_authenticated():
		title = "Register"
		form = SignUpForm(request.POST or None)
		context = {
			"title": title,
			"form" : form
		}
		if form.is_valid():
			#form.save()
			#print request.POST['email']
			instance = form.save(commit=False)
			full_name = form.cleaned_data.get("full_name")
			if not full_name:
				full_name = "Unknown User"
			instance.full_name = full_name
			#if not instance.full_name:
			#	instance.full_name = "Unknown User"
			instance.save()
			context = {
				"title": "Thanks for registration"
			
		}
	return render(request, "signup.html", context)

# ============= navigate login page ======================
def login(request):
	return render(request, 'login.html')

# ============= navigate userdashboard page ==============
def userdashboard(request):
	 return render(request, 'userdashboard.html')

# ============= navigate mycourses page ==================
def mycourses(request):
	courses = Course.objects.all()
	return render(request, 'mycourses.html', {'courses': courses})

# ============= navigate users page ======================
def users(request):
	return render(request, 'users.html')

learning_site/views.py
from django.shortcuts import render
from django_tables2 import RequestConfig
from courses.models import Course
from courses.tables import CourseTable



#from .forms import SignUpForm
def home(request):
	# return render(request, "home.html", {})
	table = CourseTable(Course.objects.all())
	RequestConfig(request).configure(table)
	return render(request, 'home.html', {'table': table})

def cslist(request):
	table = CourseTable(Course.objects.all())
	RequestConfig(request).configure(table)
	return render(request, 'cslist/cslist.html', {'table': table})
	
# def cslist(request):
#  	return render(request, "cslist/cslist.html", {"table": Course.objects.all()})


def about(request):
	return render(request, "about.html", {})

def contact_us(request):
	return render(request, "contact_us.html", {})

def login(request):
	return render(request, "login.html", {})

def signup(reqeust):
	return render(request, "signup.html", {})

courses/templates/courses/course_detail.html
{% extends 'base.html' %}

{% block head_title %}Welcome | {{ block.super }} {% endblock %}

{% block content %}
<article>
	<h2>{{ course.title }}</h2>
	{{ course.description }}
	<section>
		{% for step in course.step_set.all %}
			<h3><a href="{% url 'courses:step' course_pk=step.course.pk step_pk=step.pk %}">{{ step.title }}</a></h3>
			{{ step.description }}
		{% endfor %}
	</section>
</article>
{% endblock %}

courses/templates/courses/course_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}Welcome | {{ block.super }} {% endblock %}

{% block content %}
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
    <h1>Edit Course</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
    </div>
  </div>
{% endblock %}

courses/templates/courses/course_list.html
{% extends 'base.html' %}

{% block head_title %}Welcome | {{ block.super }} {% endblock %}

{% block content %}
 <div class="row">
	<div class="col-sm-12">
		<div class="cards">
			{% for course in courses %}
				<div class="card">
					<header><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></header>
					<div class="card-copy">
						{{ course.description }}
					</div><!-- end card-copy -->
				</div><!-- end card -->
			{% endfor %}
		</div><!-- end cards -->
	</div><!-- end col-sm-12 -->
</div><!-- end row -->
{% endblock %}

courses/templates/courses/new_course.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Welcome | {{ block.super }} {% endblock %}

{% block content %}
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
    <h1>Add New Course</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
    </div>
  </div>
{% endblock %}

courses/templates/courses/step_detail.html
{% extends "base.html" %}

{% block title %}{{ step.title }} - {{ step.course.title }}{% endblock %}

{% block content %}
<article>
    <h2><a href="{%url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></h2>
    <h3>{{ step.title }}</h3>
    {{ step.content|linebreaks }}
</article>
{% endblock %}

templates/about.html
{% extends "base.html" %}

{% block head_title %}Welcome | {{ block.super }} {% endblock %}

{% block content %}
<div class="row">
	<div class="col-sm-12">
    	<h1>About Us</h1> 
    </div><!-- end col-sm-12-->
 </div><!-- end row -->

 <div class="row">
 	<div class="col-sm-12">
 		<article><p>KosAcademy it is a new company that offers online computer programming courses for all peoples who want to learn different programming languages.</p>
 		</article>
	
 	</div><!-- end col-sm-12 -->
 </div><!-- end row -->
{% endblock %}

templates/base-copy.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
 
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block head_title %}Learnin Center{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/custom_style.css' %}">
    <link href="{% static 'css/navbar-fixed-top.css' %}" rel="stylesheet">
    {% include 'head_css.html' %}
  </head>

  <body>
  <div class="container">
     <nav>
        <a href="{% url 'views.home' %}">Home</a>
        <a href="{% url 'courses:list' %}">Courses</a>
      </nav> 

         
    {% block content %}
    {% endblock%}
  </div><!-- end container -->
  </body>
</html>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block head_title %}KosAcademy{% endblock %}</title>
    
    {% block extra_css %}
    {% endblock %}

    {% include 'head_css.html'%}

  </head>

  <body>
  {% include 'navbar.html' %}

    <div class="container">
     {% block main %}
        <div class="jumbotron">
          {% block main_content %}        
          {% endblock %}
        </div>
     {% endblock %}

     {% block content %}
     {% endblock %}

     {% block table2_table %}
     {% endblock %}
    </div> <!-- end container -->

    {% include 'javascript.html' %}

  </body>
</html>

templates/contact_us.html
{% extends 'base.html' %}

 {% block head_title %}Welcome | {{ block.super}}{% endblock %}

 <!--This is contact form -->
{% block content %}
{% if title %}
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<h2 class="text-align-center">{{ title}}</h2>
		</div><!--end col-sm-6-->
	</div> <!--end row-->
{% endif %}

	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
		<form method='POST' action=''>{% csrf_token %}

			{{ form }}

		<input class="btn btn-default" type='submit' value='Send' />

		</form>
		</div><!-- end col-sm-6 -->
	</div><!-- end row -->
{% endblock %}

templates/cslist---.html
{% load render_table from django_tables2 %}
{% load staticfiles %}

<!doctype html>
<html>
    <head>
    	<link rel="stylesheet" href="{{ STATIC_URL }}django_tables2/themes/paleblue/css/screen.css" />
	<!-- <link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" /> -->
    </head>
    <body>
    	   {% render_table table %}
    </body>
</html>

templates/cslist/cslist-copy.html
{% load render_table from django_tables2 %}
{% load staticfiles %}

<!doctype html>
<html>
    <head>
  
	<link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" />
    </head>
    <body>
    	   {% render_table table %}
    </body>
</html>

templates/cslist/cslist.html
{% load render_table from django_tables2 %}
{% load staticfiles %}

<!doctype html>
<html>
    <head>
  
	<link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" />
    </head>
    <body>
    	   {% render_table table %}
    </body>
</html>

templates/forms.html
<form method="POST" action="">{% csrf_token %}
{{ form.as_p }}

<input type="submit" value="Submit" />
</form>

templates/head_css.html
 {% load staticfiles %}

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <!-- <link href="navbar-static-top.css" rel="stylesheet"> -->
    <link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom_style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" />

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
   <!-- <script src="../../assets/js/ie-emulation-modes-warning.js"></script>-->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

templates/home.html
 {% extends 'base.html' %}
{% load render_table from django_tables2 %}
{% load staticfiles %}

 {% block head_title %}Welcome | {{ block.super}}{% endblock %}

{% block main_content %}
{% if not user.is_authenticated %}
	<div class="row">
		<div class="col-sm-12">
		 <h1>Programming Training Classes</h1>
		        <p>Whether you're looking for customized in-person Programming training for a private group, a public online Programming class you can join, or a self-paced Programming course you can start immediately, KosAcademy has the solution for you.
		        <p>Start today and take your future in your hands.</p>
		        <p>
		          <a class="btn btn-lg btn-primary" href="{% url 'auth_login' %}" role="button">Start Here &raquo;</a>
		        </p>
		</div> <!-- end col-sm-12 -->
	</div> <!-- end row -->
{% endif %}
{% endblock %}

{% block table2_table %}
<h1>Programming Course Outlines </h1>
{% render_table table %}
{% endblock %}

templates/mycourses-copy.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Welcome | {{ block.super }} {% endblock %}

{% block content %}
<div class="row">
	<div class="col-sm-8">
    	<h1>My Courses</h1> 
    </div><!-- end col-sm-8-->
    	<div class="col-sm-4 pull-right">
    		<a href="{% url 'new_course' %}"><button type="button" class="btn btn-warning">Add Course</button></a>
    	</div><!-- end col-sm-4 -->
 </div><!-- end row -->

 <div class="row">
 	<div class="col-sm-12">
			<table class="table">  
			        <thead>  
			          <tr>  
			            <th>Student-ID</th>  
			            <th>First Name</th>  
			            <th>Last Name</th>  
			            <th>Grade</th>  
			          </tr>  
			        </thead>  
			        <tbody>  
			          <tr>  
			            <td>001</td>  
			            <td>Rammohan </td>  
			            <td>Reddy</td>  
			            <td>A+</td>  
			          </tr>  
			          <tr>  
			            <td>002</td>  
			            <td>Smita</td>  
			            <td>Pallod</td>  
			            <td>A</td>  
			          </tr>  
			          <tr>  
			            <td>003</td>  
			            <td>Rabindranath</td>  
			            <td>Sen</td>  
			            <td>A+</td>  
			          </tr>  
			        </tbody>  
			      </table>
 	</div><!-- end col-sm-12 -->
 </div><!-- end row -->
{% endblock %}

templates/mycourses.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Welcome | {{ block.super }} {% endblock %}

{% block content %}
<div class="row">
	<div class="col-sm-8">
    	<h1>My Courses</h1> 
    </div><!-- end col-sm-8-->
    	<div class="col-sm-4 pull-right">
    		<a href="{% url 'new_course' %}"><button type="button" class="btn btn-success">Add Course</button></a>
    	</div><!-- end col-sm-4 -->
 </div><!-- end row -->

 <div class="row">
 	<div class="col-sm-10">
 
			<table class="table">  
			        <thead>  
			          <tr>  
			            <th>ID</th>  
			            <th>Course Name</th>   
			            <th>Teacher</th>			         
			          </tr>  
			        </thead> 
			        <tbody> 
			        {% for course in courses %}    
			          <tr>			          		
			            <td>{{ course.id}}</td>  
			            <td>{{ course.title }} </td> 
			            <td>Ridvan Aliu</td>  
			            <td><a class="btn btn-default" href="{% url "course_edit" pk=course.pk %}">Edit</a>
			       
			            <a href="{% url 'new_course' %}"><button type="button" class="btn btn-danger">Delete</button></a></td>
			          </tr>
			          {% endfor %}
			        </tbody>  
			      </table>
	
 	</div><!-- end col-sm-12 -->
 </div><!-- end row -->
{% endblock %}

templates/navbar.html
<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top mynavbar">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">KosAcademy</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          {% if request.user.is_authenticated %}
           <li><a href="{% url 'userdashboard' %}">userdashboard</a></li>
            <li><a href="{% url 'mycourses' %}">My Courses</a></li>
             <li><a href="{% url 'users' %}">Users</a></li>
             <!-- <li><a href="{% url 'new_course' %}">Add Course</a></li> -->
             
             {% else %}
            <li><a href="{% url 'views.home' %}">Home</a></li>
            <li><a href="{% url 'courses:list' %}">Courses</a></li>
        
            <li><a href="{% url 'about' %}">About</a></li>
         <!--    <li><a href="{% url 'contact' %}">Contact</a></li> -->
            {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
          {% if request.user.is_authenticated %}
          <li><a href="{% url 'auth_logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'auth_login' %}">Login</a></li>
          <li><a href="{% url 'registration_register' %}">Register</a></li>
          {% endif %}
            <!-- <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'signup' %}">Sign Up</a></li> -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

templates/signup.html
{% extends 'base.html' %}

 {% block head_title %}Welcome | {{ block.super}}{% endblock %}

 {% block content %}
    <h1>{{title}}</h1>
    <form method='POST' action=''>{% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Submit" />
   <!-- <input type="text">
    <input> -->
    </form>
{% endblock %}

templates/userdashboard.html
{% extends "base.html" %}

{% block head_title %}Welcome | {{ block.super }} {% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-4 col-sm-offset-2">
      <h1>  All Courses</h1> 
    </div><!-- end col-sm-6-->
      <div class="col-sm-4 col-sm-offset-2 pull-right">
      <h1>All Users</h1>
      </div><!-- end col-sm-6 -->
 </div><!-- end row -->

 <div class="row">
  <div class="col-sm-10">
  
  </div><!-- end col-sm-12 -->
 </div><!-- end row -->
{% endblock %}

templates/users.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Welcome | {{ block.super }} {% endblock %}

{% block content %}
<div class="row">
	<div class="col-sm-12">
    	<h1>All Users</h1> 
    </div><!-- end col-sm-8-->
 </div><!-- end row -->
 <div class="row">
 	<div class="col-sm-10">
 
			<table class="table">  
			        <thead>  
			          <tr>  
			            <th>ID</th>  
			            <th>User Name</th>   			         
			          </tr>  
			        </thead> 
			        <tbody> 
			        {% for user in users %}    
			          <tr>			          		
			            <td>{{ user.id}}</td>  
			            <td>{{ user.name }} </td>   
			            <td><a class="btn btn-default" href="{% url "course_edit" pk=course.pk %}">Edit</a>
			       
			            <a href="{% url 'new_course' %}"><button type="button" class="btn btn-danger">Delete</button></a></td>
			          </tr>
			          {% endfor %}
			        </tbody>  
			      </table>
	
 	</div><!-- end col-sm-12 -->
 </div><!-- end row -->
{% endblock %}